### ISSUE TITLE
Mistake in README ~ arguments

### ISSUE THREAD

**Issue by annabel-uzl** [GoogleCloudPlatform/bundler_for_fhir_profile_validation_resources#3]
Hi
I'm not able to push my change request, so apologies for the issue-creation:
In the README, it says the input arguments are `--input-dir` and `--output-dir`. 
However, they need to be `--input_dir` and -`-output_dir` respectively.

**Comment by bsun94** [comment]
Thanks for pointing it out Annabel, we'll fix the issue & push it out
